import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import AOSProvider from "@/libs/AOSProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body>
        <AOSProvider />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
